export const MyWorkItemDb = [
  {
    title: "KatieArt E-commerce",
    imageUrl: "artwork.png",
    description:
      "This e-commerce project is a front-end web application building by using React.js, Redux, Styled components, ans Sass. It is inspired by a web development course on Udemy. This online store displays different types of artworks and allows a user to register, sign in, add a product to a shopping cart, and preceed to check out. Firebase and Stripe API are integreated into the app to enable the user authentication and check out features.",
    demoUrl: "https://kitiya-artwork.netlify.app/",
    githubUrl: "https://github.com/kitiya/react-artwork",
    techStack: [
      { icon: "html5", title: "HTML 5" },
      { icon: "css3", title: "CSS 3" },
      { icon: "sass", title: "SASS" },
      { icon: "styled-components", title: "Styled-Components" },
      { icon: "javascript", title: "JavaScript" },
      { icon: "react", title: "React.js" },
      { icon: "react-router", title: "React Router" },
      { icon: "redux", title: "Redux" },
      { icon: "firebase", title: "Firebase" },
      { icon: "stripe", title: "Stripe Payment" },
      { icon: "npm", title: "NPM" },
      { icon: "git", title: "Git" },
      { icon: "netlify", title: "Netlify" },
    ],
  },
  {
    title: "Camps & Classes for Kids",
    imageUrl: "beaver_home.png",
    description:
      "This project was built when I joined the ComIT bootcamp in 2019. It is a full-stack web application using Spring Framework, MySQL, and React.js. It has a complete CRUD operation for a company to create, update, deleat, and view a camp, class, activity, or event which can be searched and filtered by class name, activity type, city, age, or business provider. RESTful API is implemented to transfer information between client and server. It is the first time I learned React which is an eye-opening experience.",
    demoUrl: "",
    githubUrl: "https://github.com/kitiya/beaver",
    techStack: [
      { icon: "java", title: "Java" },
      { icon: "spring", title: "Spring Framework" },
      { icon: "mysql", title: "MySQL" },
      { icon: "rest-api", title: "REST API" },
      { icon: "postman", title: "Postman" },
      { icon: "html5", title: "HTML 5" },
      { icon: "css3", title: "CSS 3" },
      { icon: "bootstrap", title: "Bootstrap" },
      { icon: "javascript", title: "JavaScript" },
      { icon: "react", title: "React.js" },
      { icon: "react-router", title: "React Router" },
      { icon: "npm", title: "NPM" },
      { icon: "git", title: "Git" },
    ],
  },
  {
    title: "Covid 19 Tracker",
    imageUrl: "covid_19_tracker.png",
    description:
      "The Covid-19 Tracker app was created in March 2020 to track numbers of Corona Virus cases around the globe as well as in Canada. It is a front-end web development project that uses a third party API call. I installed the Material UI library to build the user interface. The Rechart.js libary is implemented to display all the charts and graphs in this application.",
    demoUrl: "https://kitiya.github.io/covid19-tracker/#/",
    githubUrl: "https://github.com/kitiya/covid19-tracker",
    techStack: [
      { icon: "html5", title: "HTML 5" },
      { icon: "css3", title: "CSS 3" },
      { icon: "javascript", title: "JavaScript" },
      { icon: "axios", title: "Axios" },
      { icon: "react", title: "React.js" },
      { icon: "react-router", title: "React Router" },
      { icon: "material-ui", title: "Material-UI" },
      { icon: "npm", title: "NPM" },
      { icon: "git", title: "Git" },
      { icon: "github", title: "GitHub" },
      { icon: "recharts", title: "Recharts.org" },
    ],
  },
  {
    title: "Pixabay Image Finder",
    imageUrl: "pixabay_image_finder.png",
    description:
      "This is a simple front-end web application from a YouTube tutorial that helps me learn how to integrate the Material UI library to a React project. It uses a Pixabay API to allow a user to search for images from the Pixabay website. A search result can be filtered by a category, a color, and a keyword.",
    demoUrl: "https://kitiya.github.io/pixabay-image-finder/",
    githubUrl: "https://github.com/kitiya/pixabay-image-finder",
    techStack: [
      { icon: "html5", title: "HTML 5" },
      { icon: "css3", title: "CSS 3" },
      { icon: "javascript", title: "JavaScript" },
      { icon: "axios", title: "Axios" },
      { icon: "react", title: "React.js" },
      { icon: "material-ui", title: "Material-UI" },
      { icon: "npm", title: "NPM" },
      { icon: "git", title: "Git" },
      { icon: "github", title: "GitHub" },
    ],
  },
  {
    title: "Face Detection App",
    imageUrl: "smart-brain-ai.png",
    description:
      "This is a full-stack web application from a Udemy course. The main features of the project includes user authenticaion and authorization, detecting a face from an uploaded image, An image upload counter that keeps track of the total number of images uploaded by a user.  The main technology stack used in this project are Node.js, Express, PostgreSQL, and React.js.",
    demoUrl: "https://kitiya-face-detection.netlify.app/",
    githubUrl: "https://github.com/kitiya/face-detection",
    techStack: [
      { icon: "nodejs", title: "Node.js" },
      { icon: "expressjs", title: "Express.js" },
      { icon: "postgresql", title: "PostgreSQL" },
      { icon: "html5", title: "HTML 5" },
      { icon: "css3", title: "CSS 3" },
      { icon: "javascript", title: "JavaScript" },
      { icon: "react", title: "React.js" },
      { icon: "sass", title: "SASS" },
      { icon: "npm", title: "NPM" },
      { icon: "git", title: "Git" },
      { icon: "github", title: "GitHub" },
    ],
  },
];

/*
{
  title: "Basic French for Kids",
  techStack: [
    { icon: "html5", title: "HTML 5" },
    { icon: "css3", title: "CSS 3" },
    { icon: "javascript", title: "JavaScript" },
    { icon: "react", title: "React.js" },
    { icon: "material-ui", title: "Material-UI" },
    { icon: "npm", title: "NPM" },
    { icon: "git", title: "Git" },
    { icon: "github", title: "GitHub" },
  ],
  description:
    "This project was one of my first fully designed websites, it was a conceptual piece for a fictitious high end restaurant based in York. It taught me how to make an animated hamburger menu as well as some interesting hover effects over the menus. The site was made purely with HTML and CSS as no Javascript was required for functionality.",
  imageUrl: "french_for_kids.png",
},
*/
